/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaleilao;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo Torres Custódio, Mateus Assis Rocha
 *
 */
public class Pessoa extends javax.swing.JFrame implements Validacao {

    /**
     * Creates new form Pessoa
     */
    private Banco banco;
    private int codPessoa;
    private int codLogin;
    private int codPessoaExterior;
    private int codProduto;
    private int codLeilao;
    private String nome;
    private int tempoUso;
    private String estadoConservacao;
    private double preco;
    private String descricao;
    private String[] texts = new String[5];

    public Pessoa() {
        initComponents();
    }

    public Pessoa(int codPessoa, int codLogin) {
        initComponents();
        // O usuário recebe as PKs das tabelas Login e Pessoa
        this.banco = Banco.getBanco();
        this.codPessoa = codPessoa;
        this.codLogin = codLogin;
        try {
            /*
             * Recebe o código do próximo leilão e do próximo produto a serem
             * cadastrados, uma vez que o usuário nõ fornece essas informações
             * no momento do cadastro
             */
            this.codProduto = banco.retornaCodigoProduto() + 1;
            this.codLeilao = banco.retornaCodigoLeilao() + 1;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao iniciar",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
        //Métodos para carregar os comboBoxes com informações dos leilões
        carregaTodosLeiloes();
        carregaLeiloesUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboTodosLeiloes = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        comboLeiloesUsuario = new javax.swing.JComboBox();
        btAtualiza = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btLance = new javax.swing.JButton();
        txtValorLance = new javax.swing.JTextField();
        txtNumeroLeilao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btFechaLeilao = new javax.swing.JButton();
        txtSelecionaLeilao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btCadstra = new javax.swing.JButton();
        txtEstado = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtTempo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));

        comboTodosLeiloes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboLeiloesUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btAtualiza.setText("Atualiza");
        btAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizaActionPerformed(evt);
            }
        });

        btLance.setText("Dar lance");
        btLance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLanceActionPerformed(evt);
            }
        });

        jLabel8.setText("Número leilão:");

        jLabel9.setText("Lance:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btLance, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNumeroLeilao)
                    .addComponent(txtValorLance))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorLance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btLance)
                .addContainerGap())
        );

        btFechaLeilao.setText("Fechar Leilao");
        btFechaLeilao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFechaLeilaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Número leilão:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btFechaLeilao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSelecionaLeilao))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSelecionaLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btFechaLeilao)
                .addContainerGap())
        );

        btCadstra.setText("Cadastrar");
        btCadstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadstraActionPerformed(evt);
            }
        });

        jLabel1.setText("Tempo uso:");

        jLabel2.setText("Produto:");

        jLabel4.setText("Condições:");

        jLabel5.setText("Preço inicial:");

        jLabel7.setText("Descrição:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(txtTempo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtDescricao))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btCadstra, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btCadstra)
                .addGap(26, 26, 26))
        );

        jLabel10.setText("Leilões do usuário:");

        jLabel11.setText("Todos os leilões");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel6)
                .addContainerGap(359, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboLeiloesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(comboTodosLeiloes, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboLeiloesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualiza)
                    .addComponent(comboTodosLeiloes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadstraActionPerformed
        texts[0] = txtNome.getText();
        texts[1] = txtTempo.getText();
        texts[2] = txtEstado.getText();
        texts[3] = txtValor.getText();
        texts[4] = txtDescricao.getText();
        /*
         * Se todos os campos de texto forem validados com sucesso, é cadastrado
         * no banco de dados o leilão e as informações do produto relacionado a
         * ele
         */
        if (valida(texts)) {
            try {
                banco.cadastraProduto(codProduto, codLeilao, nome, tempoUso, preco,
                        estadoConservacao, descricao);
                banco.cadastraLeilao(codLeilao, codProduto, codLogin, preco);
                carregaTodosLeiloes();
                carregaLeiloesUsuario();
                JOptionPane.showMessageDialog(null, "Dados cadastrados com sucesso", "Sucesso",
                        JOptionPane.DEFAULT_OPTION);
                /* Após o registro é codProduto e codLeilao recebem +1 para que não
                 * seja necessário o cliente sair do sistema e entrar de novo para que
                 * possa criar outro leilão
                 */
                codProduto++;
                codLeilao++;
                //Todos os campos de texto são zerados
                txtNome.setText("");
                txtTempo.setText("");
                txtEstado.setText("");
                txtValor.setText("");
                txtDescricao.setText("");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro no cadastro do leilão",
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btCadstraActionPerformed

    private void btLanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLanceActionPerformed
        /*
         * Clicar neste botão faz o programa verificar as exceções para os
         * campos de texto, e chama o método verificaLance. Este método registra
         * o usuário como o arrematante da tabela leilão (aquele que até agora
         * deu o maior lance) e muda o lance mínimo)
         */
        int tentativaLeilao = 0;
        double lance = 0;
        try {
            tentativaLeilao = Integer.parseInt(txtNumeroLeilao.getText());
            lance = Double.parseDouble(txtValorLance.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro, apenas números e campos não-nulos",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }

        try {
            banco.verificaLance(codLogin, tentativaLeilao, lance);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro de SQL ao dar lance",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btLanceActionPerformed

    private void btFechaLeilaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFechaLeilaoActionPerformed
        /*
         * Verifica as exceções de dois campos text e muda o status de um leilão
         * de aberto para fechado. Mas somente se o usuário é o criador do
         * leilão em questão
         */
        try {
            int codLeilaoFecha = Integer.parseInt(txtSelecionaLeilao.getText());
            banco.encerraLeilao(codLogin, codLeilaoFecha);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao fechar leilão",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
        // Depois de cadastrado ou não , os comboBox são atulizados automaticamente
        carregaTodosLeiloes();
        carregaLeiloesUsuario();
    }//GEN-LAST:event_btFechaLeilaoActionPerformed

    private void btAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizaActionPerformed
        //Chama métodos para atualizar as informações de leilões ativos
        carregaTodosLeiloes();
        carregaLeiloesUsuario();
    }//GEN-LAST:event_btAtualizaActionPerformed

    public void carregaTodosLeiloes() {
        /*
         * Recebe em um ArrayList de Strings, onde cada um contém o código do
         * leilão, o nome do produto e o preço atual, de todos os leilões que estão ativos
         * (verificado por um campo no banco de dados).
         */
        comboTodosLeiloes.removeAllItems(); //Remove todos os itens do comboBox antes de acrescentar
        try {
            ArrayList<String> todosLeiloes = banco.carregaLeiloes();
            for (Iterator i = todosLeiloes.iterator(); i.hasNext();) {
                comboTodosLeiloes.addItem(i.next());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar os leilões ativos",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void carregaLeiloesUsuario() {
        /*
         * Tem a mesma função do método carregaTodosLeiloes(), mas, neste
         * caso, carrega apenas os leilões que foram abertos pelo usuário,
         * através da sobrecarga do método carregaLeiloes()
         */
        comboLeiloesUsuario.removeAllItems();
        try {
            ArrayList<String> leiloesUsuario = banco.carregaLeiloes(codLogin);

            for (Iterator i = leiloesUsuario.iterator(); i.hasNext();) {

                comboLeiloesUsuario.addItem(i.next());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar os leilões ativos",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Valida todos os campos de texto transformando-os em Strings(método da interface)
    @Override
    public boolean valida(String[] texts) {
        //Verifica se existem campos nulos
        for (int i = 0; i < 5; i++) {
            if (texts[i].length() < 1) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Erro",
                        JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        this.nome = texts[0];
        //Valida tempo de uso
        try {
            this.tempoUso = Integer.parseInt(texts[1]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Coloque o tempo de uso em meses",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        //Armazena estado de conservação 
        this.estadoConservacao = texts[2];

        //Valida preço
        try {
            this.preco = Double.parseDouble(texts[3]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Preço campo numérico",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        //Armazena descricao
        this.descricao = texts[4];

        return true;
    }

    /**
     * @param args the command line arguments
     */
    //Código auto-gerado
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Pessoa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualiza;
    private javax.swing.JButton btCadstra;
    private javax.swing.JButton btFechaLeilao;
    private javax.swing.JButton btLance;
    private javax.swing.JComboBox comboLeiloesUsuario;
    private javax.swing.JComboBox comboTodosLeiloes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumeroLeilao;
    private javax.swing.JTextField txtSelecionaLeilao;
    private javax.swing.JTextField txtTempo;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorLance;
    // End of variables declaration//GEN-END:variables
}
